---
- name: Deploy MariaDB, Node Exporter and Firewall
  hosts: server1
  become: yes

  vars:
    open_ports:
      - 22    # SSH
      - 3306  # MariaDB
      - 9100  # Node Exporter

  roles:
    - mariadb
    - prometheus
    - firewall

- name: Deploy Docker, Prometheus and Grafana
  hosts: server2
  become: yes

  roles:
    - docker
    - prometheus
    - grafana
